allow setting of autoupdate-parameters during cluster creation
fi-ts/cloudctl pull request #91
Opened 2021-08-02 05:27 UTC by mwennrich

2021-08-02 06:21 UTC, Gerrit91 requested changes
This PR contradicts with the mechanism for auo-determining these values depending on cluster purpose introduced in cloud-api!172. Therefore, I would like to suggest changing the implementation to only sent the `V1MaintenanceAutoUpdate` when a user specifically passes the values through command line (should be able to be achieved when using `viper.IsSet`).

2021-10-20 11:41 UTC, majst01 commented
Updated this pr with current master, i think we should take this now ?

2022-03-01 10:26 UTC, Gerrit91 commented
This PR should be merged. We should consider the following changes:

- [ ] Default auto updates for new `evaluation` purpose clusters to `true`
- [ ] Show small arrow up behind version when auto updates are enabled?
- [ ] Add hint to auto updates are enabled when changing purpose from `evaluation` to `other-purpose`.

2022-03-02 10:37 UTC, majst01 approved these changes

2022-03-02 16:09 UTC, merged